# Generated by Django 5.2.17 on 2026-08-20 18:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0002_logistics_permissions'),
        ('sales', '0004_orderitem_product_quotationitem_product'),
        ('warehouse', '0003_warehouse_role_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('dispatch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dispatch_number', models.CharField(max_length=50, unique=True)),
                ('scheduled_dispatch_date', models.DateField()),
                ('actual_dispatch_date', models.DateTimeField(blank=True, null=True)),
                ('dispatch_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('HANDED_OVER', 'Handed Over'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='SCHEDULED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='logistics.delivery')),
                ('handed_over_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handed_over_dispatches', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='sales.order')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_dispatches', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-scheduled_dispatch_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('challan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('challan_number', models.CharField(max_length=50, unique=True)),
                ('challan_date', models.DateField()),
                ('received_by', models.CharField(blank=True, max_length=150)),
                ('vehicle_number_snapshot', models.CharField(max_length=50)),
                ('driver_name_snapshot', models.CharField(max_length=200)),
                ('delivery_address', models.TextField()),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('ISSUED', 'Issued'), ('ACKNOWLEDGED', 'Acknowledged'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_challans', to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='challan', to='dispatch.dispatch')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchDocument',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('DELIVERY_CHALLAN', 'Delivery Challan'), ('PACKING_LIST', 'Packing List'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='dispatch/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='dispatch.dispatch')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('dispatch_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('package_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dispatch.dispatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='warehouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchStatusHistory',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('HANDED_OVER', 'Handed Over'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_status_changes', to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='dispatch.dispatch')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['dispatch_status', 'scheduled_dispatch_date'], name='dispatch_di_dispatc_6a946d_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['order'], name='dispatch_di_order_i_57378f_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['delivery'], name='dispatch_di_deliver_048445_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatch',
            constraint=models.UniqueConstraint(condition=models.Q(('dispatch_status__in', ['CANCELLED']), _negated=True), fields=('order',), name='one_active_dispatch_per_order'),
        ),
        migrations.AddConstraint(
            model_name='dispatchitem',
            constraint=models.UniqueConstraint(fields=('dispatch', 'product'), name='unique_dispatch_product'),
        ),
    ]
