# Generated by Django 5.2.17 on 2026-08-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_reference',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product_reference',
        ),
    ]
