# Generated by Django 5.2.17 on 2026-08-20 18:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0004_orderitem_product_quotationitem_product'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_number', models.CharField(max_length=50, unique=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='CREATED', max_length=25)),
                ('delivery_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sales.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('status_history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=25)),
                ('new_status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], max_length=25)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_status_changes', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='logistics.delivery')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_type', models.CharField(max_length=50)),
                ('license_issue_date', models.DateField()),
                ('license_expiry', models.DateField()),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('ON_DELIVERY', 'On Delivery'), ('ON_LEAVE', 'On Leave'), ('UNAVAILABLE', 'Unavailable'), ('SUSPENDED', 'Suspended')], default='AVAILABLE', max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='driver_profile', to='workforce.employee')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='logistics.driver'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('route_number', models.CharField(max_length=50, unique=True)),
                ('origin_address', models.TextField()),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_state', models.CharField(max_length=100)),
                ('origin_pincode', models.CharField(max_length=20)),
                ('destination_address', models.TextField()),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_state', models.CharField(max_length=100)),
                ('destination_pincode', models.CharField(max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estimated_duration_minutes', models.PositiveIntegerField()),
                ('route_algorithm', models.CharField(choices=[('DIJKSTRA', 'Dijkstra'), ('A_STAR', 'A*'), ('SHORTEST_PATH', 'Shortest Path'), ('MANUAL', 'Manual'), ('OTHER', 'Other')], default='MANUAL', max_length=30)),
                ('route_status', models.CharField(choices=[('PLANNED', 'Planned'), ('OPTIMIZED', 'Optimized'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('planned_start_time', models.DateTimeField(blank=True, null=True)),
                ('planned_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='logistics.route'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('VAN', 'Van'), ('PICKUP', 'Pickup'), ('TEMPO', 'Tempo'), ('OTHER', 'Other')], max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('manufacturing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('capacity_unit', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('OTHER', 'Other')], max_length=20)),
                ('registration_date', models.DateField()),
                ('registration_expiry', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('pollution_certificate_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=25)),
                ('current_odometer', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vehicle_number'],
                'indexes': [models.Index(fields=['status', 'vehicle_type'], name='logistics_v_status_f4f931_idx')],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='logistics.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('maintenance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('ROUTINE_SERVICE', 'Routine Service'), ('REPAIR', 'Repair'), ('INSPECTION', 'Inspection'), ('TYRE_CHANGE', 'Tyre Change'), ('OIL_CHANGE', 'Oil Change'), ('OTHER', 'Other')], max_length=30)),
                ('service_date', models.DateField()),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('odometer_reading', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField()),
                ('service_provider', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='logistics.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['availability_status'], name='logistics_d_availab_975b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_status'], name='logistics_r_route_s_69da15_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin_city', 'destination_city'], name='logistics_r_origin__ad7575_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_status'], name='logistics_d_deliver_83c72e_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['driver', 'delivery_status'], name='logistics_d_driver__342b85_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['vehicle', 'delivery_status'], name='logistics_d_vehicle_83876e_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order'], name='logistics_d_order_i_1fe95c_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(condition=models.Q(('delivery_status__in', ['CREATED', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY'])), fields=('order',), name='one_active_delivery_per_order'),
        ),
    ]
