# Generated by Django 5.2.17 on 2026-08-20 17:41

import django.core.validators
import django.db.models.deletion
import recruitment.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('candidate_code', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('highest_qualification', models.CharField(max_length=150)),
                ('total_experience_years', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_company', models.CharField(blank=True, max_length=150)),
                ('current_designation', models.CharField(blank=True, max_length=150)),
                ('notice_period_days', models.PositiveIntegerField(default=0)),
                ('candidate_status', models.CharField(choices=[('NEW', 'New'), ('SCREENING', 'Screening'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_candidate', to='workforce.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('resume_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=recruitment.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_text', models.TextField(blank=True)),
                ('parsing_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('candidate_skill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency_level', models.CharField(blank=True, max_length=50)),
                ('years_of_experience', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('RESUME_PARSER', 'Resume Parser'), ('AI_SCREENING', 'AI Screening')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['skill_name'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_SCREENING', 'Under Screening'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEWED', 'Interviewed'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=30)),
                ('screening_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('recruiter_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.candidate')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.candidateresume')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interview_round', models.PositiveIntegerField(default=1)),
                ('interview_type', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('PHONE', 'Phone')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_interviews', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='recruitment.jobapplication')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_code', models.CharField(max_length=50, unique=True)),
                ('job_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('minimum_experience', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('minimum_qualification', models.CharField(max_length=150)),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('number_of_openings', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_job_positions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_positions', to='workforce.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_positions', to='workforce.designation')),
            ],
            options={
                'ordering': ['-opening_date', 'job_title'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.jobposition'),
        ),
        migrations.CreateModel(
            name='RecruitmentScreening',
            fields=[
                ('screening_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_version', models.CharField(max_length=100)),
                ('skills_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('education_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('experience_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('recommendation', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('CONSIDER', 'Consider'), ('NOT_RECOMMENDED', 'Not Recommended')], max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('screened_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='recruitment.jobapplication')),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_screenings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-screened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['candidate_status', 'created_at'], name='recruitment_candida_eb7acc_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateresume',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('candidate',), name='one_primary_resume_per_candidate'),
        ),
        migrations.AddConstraint(
            model_name='candidateskill',
            constraint=models.UniqueConstraint(fields=('candidate', 'skill_name'), name='unique_candidate_skill'),
        ),
        migrations.AddConstraint(
            model_name='interview',
            constraint=models.UniqueConstraint(fields=('application', 'interview_round'), name='unique_interview_round'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['status', 'opening_date'], name='recruitment_status_c57388_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['job_code'], name='recruitment_job_cod_c0a633_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['application_status', 'application_date'], name='recruitment_applica_a73450_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('application_status__in', ['REJECTED', 'WITHDRAWN']), _negated=True), fields=('candidate', 'job'), name='one_active_application_per_job'),
        ),
    ]
